export const Actions = {
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",
  SET_MESSAGE: "SET_MESSAGE",
    ADD_NEW_FILE: "ADD_NEW_FILE",
    CLEARING_DATA: "CLEARING_DATA",
  SET_FILES: 'SET_FILES',
  SET_ADMIN: "SET_ADMIN",
  REMOVE_ALERT:'REMOVE_ALERT'
};
